---
pyramid: mayan

avatar: jaguar_shield

sarcophagus:
  type: green_jadeite_box
  inscription: "Here lies the Great Shield Jaguar. 4-Katun ahpo. The captor of Ah-Ahaual, a blood lord of Yaxchilan"
  summon_spell: "Thank you to the great anscestors and fathers of time, 4 Ahau 8 Cumku, I invoke the divine K'awiil as to speak with Shield Jaguar"


